name: realtimedata
channels:
  - conda-forge
dependencies:
  - numpy=1.19.2
  - pandas=1.1.3
  - pip=20.2.4
  - python=3.7.9
  - adal
  - msal
  - requests
  - hvplot
  - panel
  - tqdm
  - pip:
    - azure-iot-device==2.4.0
    - xmltodict==0.12.0
